#! /usr/bin/env bash

#### 2. Script Setup ####
# It's useful to exit the bash script when a command exits with a non-zero status
# as the following commands must be run successfully in sequence for expected results.

set -e # exit entire script when command exits with non-zero status

# Install dependencies
npm install

# Publish `testing` release
expo publish --release-channel testing --non-interactive

# Start building standalone android build using `testing` release channel
expo build:android --release-channel testing --non-interactive --no-publish

# Download the built android binary
curl -o app.apk "$(expo url:apk --non-interactive)"

# Start building standalone ios build using 'testing' release channel
expo build:ios --release-channel testing --non-interactive --no-publish

#Download the artifact to current directory as 'app.ipa'
curl -o app.ipa "$(expo url:ipa --non-interactive)"
